//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestShipmentPortal.BookingPortalV3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gtx.nu/ShipmentPortalV3/", ConfigurationName="BookingPortalV3.V3BookingSoap")]
    public interface V3BookingSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gtx.nu/ShipmentPortalV3/Ping", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gtx.nu/ShipmentPortalV3/Exception", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Exception(int code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gtx.nu/ShipmentPortalV3/Booking", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestShipmentPortal.BookingPortalV3.V3dResponse Booking(string accessUsername, string accessPassword, TestShipmentPortal.BookingPortalV3.V3dRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gtx.nu/ShipmentPortalV3/")]
    public partial class V3dRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private V3cOperationCode operationCodeField;
        
        private string usernameField;
        
        private string passwordField;
        
        private uint accountIdField;
        
        private V3cShipmentType shipmentTypeField;
        
        private V3cIncoTerms incotermField;
        
        private uint salesproductIdField;
        
        private System.DateTime shippingDateField;
        
        private string descriptionField;
        
        private V3dParcel[] parcelListField;
        
        private V3cExportType exportTypeField;
        
        private V3dUploadDocument[] uploadDocumentListField;
        
        private V3cImageEncoding imageEncodingField;
        
        private V3cWaybillImageFormat waybillImageFormatField;
        
        private V3cWaybillReturnCode waybillReturnCodeField;
        
        private string wayBillReturnEmailField;
        
        private decimal customsValueField;
        
        private string customsCurrencyCodeField;
        
        private decimal insuranceValueField;
        
        private string insuranceCurrencyCodeField;
        
        private bool insuredByCarrierField;
        
        private bool s01ReceiverPaysField;
        
        private string s01PayingAccountNumberField;
        
        private bool s02ReceiverPaysField;
        
        private string s02PayingAccountNumberField;
        
        private V3cDangerousGoodsAccessibilityType dangerousGoodsAccessibilityTypeField;
        
        private bool notifyReceiverField;
        
        private V3dService[] additionalServiceListField;
        
        private V3dAddress addressPickupField;
        
        private V3dAddress addressReceiverField;
        
        private V3dAddress addressSenderField;
        
        private V3dAddress addressReturnField;
        
        private V3cPickupHandling pickupHandlingField;
        
        private V3cPickupDelivery pickupDeliveryField;
        
        private System.DateTime pickupFromField;
        
        private System.DateTime pickupUntilField;
        
        private string dropPointField;
        
        private string deliveryNotificationSmsField;
        
        private string deliveryNotificationEmailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public V3cOperationCode OperationCode {
            get {
                return this.operationCodeField;
            }
            set {
                this.operationCodeField = value;
                this.RaisePropertyChanged("OperationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public uint AccountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
                this.RaisePropertyChanged("AccountId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public V3cShipmentType ShipmentType {
            get {
                return this.shipmentTypeField;
            }
            set {
                this.shipmentTypeField = value;
                this.RaisePropertyChanged("ShipmentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public V3cIncoTerms Incoterm {
            get {
                return this.incotermField;
            }
            set {
                this.incotermField = value;
                this.RaisePropertyChanged("Incoterm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public uint SalesproductId {
            get {
                return this.salesproductIdField;
            }
            set {
                this.salesproductIdField = value;
                this.RaisePropertyChanged("SalesproductId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=7)]
        public System.DateTime ShippingDate {
            get {
                return this.shippingDateField;
            }
            set {
                this.shippingDateField = value;
                this.RaisePropertyChanged("ShippingDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ParcelList", Order=9)]
        public V3dParcel[] ParcelList {
            get {
                return this.parcelListField;
            }
            set {
                this.parcelListField = value;
                this.RaisePropertyChanged("ParcelList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public V3cExportType ExportType {
            get {
                return this.exportTypeField;
            }
            set {
                this.exportTypeField = value;
                this.RaisePropertyChanged("ExportType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UploadDocumentList", Order=11)]
        public V3dUploadDocument[] UploadDocumentList {
            get {
                return this.uploadDocumentListField;
            }
            set {
                this.uploadDocumentListField = value;
                this.RaisePropertyChanged("UploadDocumentList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public V3cImageEncoding ImageEncoding {
            get {
                return this.imageEncodingField;
            }
            set {
                this.imageEncodingField = value;
                this.RaisePropertyChanged("ImageEncoding");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public V3cWaybillImageFormat WaybillImageFormat {
            get {
                return this.waybillImageFormatField;
            }
            set {
                this.waybillImageFormatField = value;
                this.RaisePropertyChanged("WaybillImageFormat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public V3cWaybillReturnCode WaybillReturnCode {
            get {
                return this.waybillReturnCodeField;
            }
            set {
                this.waybillReturnCodeField = value;
                this.RaisePropertyChanged("WaybillReturnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string WayBillReturnEmail {
            get {
                return this.wayBillReturnEmailField;
            }
            set {
                this.wayBillReturnEmailField = value;
                this.RaisePropertyChanged("WayBillReturnEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public decimal CustomsValue {
            get {
                return this.customsValueField;
            }
            set {
                this.customsValueField = value;
                this.RaisePropertyChanged("CustomsValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string CustomsCurrencyCode {
            get {
                return this.customsCurrencyCodeField;
            }
            set {
                this.customsCurrencyCodeField = value;
                this.RaisePropertyChanged("CustomsCurrencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public decimal InsuranceValue {
            get {
                return this.insuranceValueField;
            }
            set {
                this.insuranceValueField = value;
                this.RaisePropertyChanged("InsuranceValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string InsuranceCurrencyCode {
            get {
                return this.insuranceCurrencyCodeField;
            }
            set {
                this.insuranceCurrencyCodeField = value;
                this.RaisePropertyChanged("InsuranceCurrencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public bool InsuredByCarrier {
            get {
                return this.insuredByCarrierField;
            }
            set {
                this.insuredByCarrierField = value;
                this.RaisePropertyChanged("InsuredByCarrier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public bool S01ReceiverPays {
            get {
                return this.s01ReceiverPaysField;
            }
            set {
                this.s01ReceiverPaysField = value;
                this.RaisePropertyChanged("S01ReceiverPays");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public string S01PayingAccountNumber {
            get {
                return this.s01PayingAccountNumberField;
            }
            set {
                this.s01PayingAccountNumberField = value;
                this.RaisePropertyChanged("S01PayingAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public bool S02ReceiverPays {
            get {
                return this.s02ReceiverPaysField;
            }
            set {
                this.s02ReceiverPaysField = value;
                this.RaisePropertyChanged("S02ReceiverPays");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public string S02PayingAccountNumber {
            get {
                return this.s02PayingAccountNumberField;
            }
            set {
                this.s02PayingAccountNumberField = value;
                this.RaisePropertyChanged("S02PayingAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public V3cDangerousGoodsAccessibilityType DangerousGoodsAccessibilityType {
            get {
                return this.dangerousGoodsAccessibilityTypeField;
            }
            set {
                this.dangerousGoodsAccessibilityTypeField = value;
                this.RaisePropertyChanged("DangerousGoodsAccessibilityType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public bool NotifyReceiver {
            get {
                return this.notifyReceiverField;
            }
            set {
                this.notifyReceiverField = value;
                this.RaisePropertyChanged("NotifyReceiver");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=27)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AdditionalService")]
        public V3dService[] AdditionalServiceList {
            get {
                return this.additionalServiceListField;
            }
            set {
                this.additionalServiceListField = value;
                this.RaisePropertyChanged("AdditionalServiceList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public V3dAddress AddressPickup {
            get {
                return this.addressPickupField;
            }
            set {
                this.addressPickupField = value;
                this.RaisePropertyChanged("AddressPickup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public V3dAddress AddressReceiver {
            get {
                return this.addressReceiverField;
            }
            set {
                this.addressReceiverField = value;
                this.RaisePropertyChanged("AddressReceiver");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public V3dAddress AddressSender {
            get {
                return this.addressSenderField;
            }
            set {
                this.addressSenderField = value;
                this.RaisePropertyChanged("AddressSender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public V3dAddress AddressReturn {
            get {
                return this.addressReturnField;
            }
            set {
                this.addressReturnField = value;
                this.RaisePropertyChanged("AddressReturn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public V3cPickupHandling PickupHandling {
            get {
                return this.pickupHandlingField;
            }
            set {
                this.pickupHandlingField = value;
                this.RaisePropertyChanged("PickupHandling");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public V3cPickupDelivery PickupDelivery {
            get {
                return this.pickupDeliveryField;
            }
            set {
                this.pickupDeliveryField = value;
                this.RaisePropertyChanged("PickupDelivery");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time", Order=34)]
        public System.DateTime PickupFrom {
            get {
                return this.pickupFromField;
            }
            set {
                this.pickupFromField = value;
                this.RaisePropertyChanged("PickupFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time", Order=35)]
        public System.DateTime PickupUntil {
            get {
                return this.pickupUntilField;
            }
            set {
                this.pickupUntilField = value;
                this.RaisePropertyChanged("PickupUntil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=36)]
        public string DropPoint {
            get {
                return this.dropPointField;
            }
            set {
                this.dropPointField = value;
                this.RaisePropertyChanged("DropPoint");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=37)]
        public string DeliveryNotificationSms {
            get {
                return this.deliveryNotificationSmsField;
            }
            set {
                this.deliveryNotificationSmsField = value;
                this.RaisePropertyChanged("DeliveryNotificationSms");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=38)]
        public string DeliveryNotificationEmail {
            get {
                return this.deliveryNotificationEmailField;
            }
            set {
                this.deliveryNotificationEmailField = value;
                this.RaisePropertyChanged("DeliveryNotificationEmail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gtx.nu/ShipmentPortalV3/")]
    public enum V3cOperationCode {
        
        /// <remarks/>
        Test,
        
        /// <remarks/>
        Live,
        
        /// <remarks/>
        Sandbox,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gtx.nu/ShipmentPortalV3/")]
    public enum V3cShipmentType {
        
        /// <remarks/>
        Document,
        
        /// <remarks/>
        NonDocument,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gtx.nu/ShipmentPortalV3/")]
    public enum V3cIncoTerms {
        
        /// <remarks/>
        DAP,
        
        /// <remarks/>
        DDP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gtx.nu/ShipmentPortalV3/")]
    public partial class V3dParcel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal lengthField;
        
        private decimal widthField;
        
        private decimal heightField;
        
        private decimal weightField;
        
        private decimal dryIceWeightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
                this.RaisePropertyChanged("Length");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("Width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("Height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
                this.RaisePropertyChanged("Weight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal DryIceWeight {
            get {
                return this.dryIceWeightField;
            }
            set {
                this.dryIceWeightField = value;
                this.RaisePropertyChanged("DryIceWeight");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gtx.nu/ShipmentPortalV3/")]
    public partial class V3dBinaryImage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private V3cImageType imageTypeField;
        
        private V3cImageEncoding imageEncodingField;
        
        private string imageBase64Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public V3cImageType ImageType {
            get {
                return this.imageTypeField;
            }
            set {
                this.imageTypeField = value;
                this.RaisePropertyChanged("ImageType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public V3cImageEncoding ImageEncoding {
            get {
                return this.imageEncodingField;
            }
            set {
                this.imageEncodingField = value;
                this.RaisePropertyChanged("ImageEncoding");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ImageBase64 {
            get {
                return this.imageBase64Field;
            }
            set {
                this.imageBase64Field = value;
                this.RaisePropertyChanged("ImageBase64");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gtx.nu/ShipmentPortalV3/")]
    public enum V3cImageType {
        
        /// <remarks/>
        Undefined,
        
        /// <remarks/>
        WaybillHead,
        
        /// <remarks/>
        WaybillParcel,
        
        /// <remarks/>
        Multipage,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gtx.nu/ShipmentPortalV3/")]
    public enum V3cImageEncoding {
        
        /// <remarks/>
        PDF,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gtx.nu/ShipmentPortalV3/")]
    public partial class V3dStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fieldNameField;
        
        private string severityField;
        
        private string textField;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FieldName {
            get {
                return this.fieldNameField;
            }
            set {
                this.fieldNameField = value;
                this.RaisePropertyChanged("FieldName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
                this.RaisePropertyChanged("Severity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gtx.nu/ShipmentPortalV3/")]
    public partial class V3dResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string requestIdField;
        
        private bool successField;
        
        private string statusTextField;
        
        private V3cDirection directionField;
        
        private V3dStatus[] statusListField;
        
        private string carrierNameField;
        
        private string carrierProductField;
        
        private decimal billedWeightField;
        
        private decimal shipmentCostField;
        
        private decimal remoteAreaServiceCostField;
        
        private decimal oilChargeCostField;
        
        private decimal totalCostField;
        
        private string wayBillNumberHeadField;
        
        private string[] parcelWaybillnumberListField;
        
        private V3dBinaryImage[] binaryImageListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RequestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("RequestId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StatusText {
            get {
                return this.statusTextField;
            }
            set {
                this.statusTextField = value;
                this.RaisePropertyChanged("StatusText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public V3cDirection Direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
                this.RaisePropertyChanged("Direction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public V3dStatus[] StatusList {
            get {
                return this.statusListField;
            }
            set {
                this.statusListField = value;
                this.RaisePropertyChanged("StatusList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CarrierName {
            get {
                return this.carrierNameField;
            }
            set {
                this.carrierNameField = value;
                this.RaisePropertyChanged("CarrierName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CarrierProduct {
            get {
                return this.carrierProductField;
            }
            set {
                this.carrierProductField = value;
                this.RaisePropertyChanged("CarrierProduct");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal BilledWeight {
            get {
                return this.billedWeightField;
            }
            set {
                this.billedWeightField = value;
                this.RaisePropertyChanged("BilledWeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal ShipmentCost {
            get {
                return this.shipmentCostField;
            }
            set {
                this.shipmentCostField = value;
                this.RaisePropertyChanged("ShipmentCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal RemoteAreaServiceCost {
            get {
                return this.remoteAreaServiceCostField;
            }
            set {
                this.remoteAreaServiceCostField = value;
                this.RaisePropertyChanged("RemoteAreaServiceCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public decimal OilChargeCost {
            get {
                return this.oilChargeCostField;
            }
            set {
                this.oilChargeCostField = value;
                this.RaisePropertyChanged("OilChargeCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public decimal TotalCost {
            get {
                return this.totalCostField;
            }
            set {
                this.totalCostField = value;
                this.RaisePropertyChanged("TotalCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string WayBillNumberHead {
            get {
                return this.wayBillNumberHeadField;
            }
            set {
                this.wayBillNumberHeadField = value;
                this.RaisePropertyChanged("WayBillNumberHead");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=13)]
        public string[] ParcelWaybillnumberList {
            get {
                return this.parcelWaybillnumberListField;
            }
            set {
                this.parcelWaybillnumberListField = value;
                this.RaisePropertyChanged("ParcelWaybillnumberList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=14)]
        public V3dBinaryImage[] BinaryImageList {
            get {
                return this.binaryImageListField;
            }
            set {
                this.binaryImageListField = value;
                this.RaisePropertyChanged("BinaryImageList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gtx.nu/ShipmentPortalV3/")]
    public enum V3cDirection {
        
        /// <remarks/>
        Undefined,
        
        /// <remarks/>
        Export,
        
        /// <remarks/>
        Import,
        
        /// <remarks/>
        ThreeWay,
        
        /// <remarks/>
        Domestic,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gtx.nu/ShipmentPortalV3/")]
    public partial class V3dAddress : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string attentionField;
        
        private string street1Field;
        
        private string street2Field;
        
        private string zipCodeField;
        
        private string cityField;
        
        private string stateCodeField;
        
        private string countryCodeField;
        
        private string phoneField;
        
        private string emailField;
        
        private string referenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Attention {
            get {
                return this.attentionField;
            }
            set {
                this.attentionField = value;
                this.RaisePropertyChanged("Attention");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Street1 {
            get {
                return this.street1Field;
            }
            set {
                this.street1Field = value;
                this.RaisePropertyChanged("Street1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Street2 {
            get {
                return this.street2Field;
            }
            set {
                this.street2Field = value;
                this.RaisePropertyChanged("Street2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
                this.RaisePropertyChanged("ZipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string StateCode {
            get {
                return this.stateCodeField;
            }
            set {
                this.stateCodeField = value;
                this.RaisePropertyChanged("StateCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
                this.RaisePropertyChanged("CountryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("Phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
                this.RaisePropertyChanged("Reference");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gtx.nu/ShipmentPortalV3/")]
    public partial class V3dService : object, System.ComponentModel.INotifyPropertyChanged {
        
        private V3cServiceCode serviceCodeField;
        
        private string[] parameterListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public V3cServiceCode ServiceCode {
            get {
                return this.serviceCodeField;
            }
            set {
                this.serviceCodeField = value;
                this.RaisePropertyChanged("ServiceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Parameter")]
        public string[] ParameterList {
            get {
                return this.parameterListField;
            }
            set {
                this.parameterListField = value;
                this.RaisePropertyChanged("ParameterList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gtx.nu/ShipmentPortalV3/")]
    public enum V3cServiceCode {
        
        /// <remarks/>
        SUNDEF,
        
        /// <remarks/>
        SDPSTD,
        
        /// <remarks/>
        DGACCS,
        
        /// <remarks/>
        DGINAC,
        
        /// <remarks/>
        DGFULL,
        
        /// <remarks/>
        DGLITB,
        
        /// <remarks/>
        DGBIOS,
        
        /// <remarks/>
        DRYICE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gtx.nu/ShipmentPortalV3/")]
    public partial class V3dUploadDocument : object, System.ComponentModel.INotifyPropertyChanged {
        
        private V3cUploadDocumentType imageTypeField;
        
        private V3cUploadDocumentEncoding imageEncodingField;
        
        private string filenameField;
        
        private string imageBase64Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public V3cUploadDocumentType ImageType {
            get {
                return this.imageTypeField;
            }
            set {
                this.imageTypeField = value;
                this.RaisePropertyChanged("ImageType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public V3cUploadDocumentEncoding ImageEncoding {
            get {
                return this.imageEncodingField;
            }
            set {
                this.imageEncodingField = value;
                this.RaisePropertyChanged("ImageEncoding");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Filename {
            get {
                return this.filenameField;
            }
            set {
                this.filenameField = value;
                this.RaisePropertyChanged("Filename");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ImageBase64 {
            get {
                return this.imageBase64Field;
            }
            set {
                this.imageBase64Field = value;
                this.RaisePropertyChanged("ImageBase64");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gtx.nu/ShipmentPortalV3/")]
    public enum V3cUploadDocumentType {
        
        /// <remarks/>
        Undefined,
        
        /// <remarks/>
        Invoice,
        
        /// <remarks/>
        ExportDeclaration,
        
        /// <remarks/>
        DangerousGoods,
        
        /// <remarks/>
        Other,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gtx.nu/ShipmentPortalV3/")]
    public enum V3cUploadDocumentEncoding {
        
        /// <remarks/>
        Undefined,
        
        /// <remarks/>
        PDF,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gtx.nu/ShipmentPortalV3/")]
    public enum V3cExportType {
        
        /// <remarks/>
        Undefined,
        
        /// <remarks/>
        Permanent,
        
        /// <remarks/>
        Temporatry,
        
        /// <remarks/>
        Return,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gtx.nu/ShipmentPortalV3/")]
    public enum V3cWaybillImageFormat {
        
        /// <remarks/>
        A4,
        
        /// <remarks/>
        LabelPrint,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gtx.nu/ShipmentPortalV3/")]
    public enum V3cWaybillReturnCode {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Immediately,
        
        /// <remarks/>
        Email,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gtx.nu/ShipmentPortalV3/")]
    public enum V3cDangerousGoodsAccessibilityType {
        
        /// <remarks/>
        NotApplicable,
        
        /// <remarks/>
        Inaccessible,
        
        /// <remarks/>
        Accessible,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gtx.nu/ShipmentPortalV3/")]
    public enum V3cPickupHandling {
        
        /// <remarks/>
        Disabled,
        
        /// <remarks/>
        Conditional,
        
        /// <remarks/>
        Unconditional,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gtx.nu/ShipmentPortalV3/")]
    public enum V3cPickupDelivery {
        
        /// <remarks/>
        Undefined,
        
        /// <remarks/>
        Email,
        
        /// <remarks/>
        Online,
        
        /// <remarks/>
        OnlineOrEmail,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface V3BookingSoapChannel : TestShipmentPortal.BookingPortalV3.V3BookingSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class V3BookingSoapClient : System.ServiceModel.ClientBase<TestShipmentPortal.BookingPortalV3.V3BookingSoap>, TestShipmentPortal.BookingPortalV3.V3BookingSoap {
        
        public V3BookingSoapClient() {
        }
        
        public V3BookingSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public V3BookingSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public V3BookingSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public V3BookingSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Ping() {
            return base.Channel.Ping();
        }
        
        public string Exception(int code) {
            return base.Channel.Exception(code);
        }
        
        public TestShipmentPortal.BookingPortalV3.V3dResponse Booking(string accessUsername, string accessPassword, TestShipmentPortal.BookingPortalV3.V3dRequest request) {
            return base.Channel.Booking(accessUsername, accessPassword, request);
        }
    }
}
